# Generated by Django 2.2.7 on 2019-11-20 10:51

import GestionConsumo.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ad', 'admin'), ('añ', 'añadir'), ('ed', 'editar')], default='añ', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionConsumo.Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('año', models.PositiveIntegerField(default=2019, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1984), GestionConsumo.models.max_value_current_year])),
                ('consumo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo', to='GestionConsumo.Activo')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='GestionConsumo.Activo')),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionConsumo.Empresa'),
        ),
    ]
