# Generated by Django 2.2.7 on 2019-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionConsumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
