# Generated by Django 2.2.7 on 2019-12-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionConsumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='co2_emitido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
