# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionconsumo', '0002_activos_consumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='roll',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ad', 'admin'), ('añ', 'añadir'), ('ed', 'editar')], default='añ', max_length=10),
        ),
    ]
