# Generated by Django 2.2.7 on 2019-12-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionConsumo', '0002_auto_20191230_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='id_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionConsumo.Activo'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionConsumo.Empresa'),
        ),
    ]
