# Generated by Django 2.2.7 on 2020-01-02 09:49

import GestionConsumo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionConsumo', '0003_auto_20191230_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='año',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), GestionConsumo.models.max_value_current_year]),
        ),
    ]
